name: AmazonLinux Base Image Build
on:
  schedule:
    - cron: '0 0 * * 6' # Weekly on Saturday at 00:00
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Get latest AmazonLinux tag
        id: get_latest_tag
        run: |
          LATEST_TAG=$(curl -s https://hub.docker.com/v2/namespaces/library/repositories/amazonlinux/tags | jq -r '.results[1].name')
          echo "Latest tag: $LATEST_TAG"
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          build-args: |-
            AZLINUX_VERSION=$LATEST_TAG
          push: false
          tags:
            - amazonlinux:latest
            - amazonlinux:$LATEST_TAG
