name: Al2023 Base Image Build
on:
  schedule:
    - cron: '0 0 * * 6' # Weekly on Saturday at 00:00
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
  jobs:
    ci:
      name: Build Image and Push
      uses: uc-cdis/.github/.github/workflows/image_build_push.yaml@master
      with:
        DOCKERFILE_LOCATION: "./al2023/Dockerfile"
        OVERRIDE_REPO_NAME: "amazonlinux"
        OVERRIDE_TAG_NAME: "baselatest-$(echo ${GITHUB_REF#refs/*/} | tr / _)"
        secrets:
          ECR_AWS_ACCESS_KEY_ID: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          ECR_AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_ROBOT_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}
