name: Build Python Base Images and Push to Quay and ECR

on: push

jobs:
  BaseAmazonLinux:
    name: AmazonLinuxLatest
    uses: uc-cdis/.github/.github/workflows/image_build_push.yaml@master
    with:
      DOCKERFILE_LOCATION: "./al2023/Dockerfile"
      OVERRIDE_REPO_NAME: "amazonlinux"
      OVERRIDE_TAG_NAME: "amazonlinuxlatest"
      USE_QUAY_ONLY: "True"
    secrets:
      ECR_AWS_ACCESS_KEY_ID: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
      ECR_AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_ROBOT_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}
