on:
  workflow_dispatch:
    inputs:
      image:
        description: "Image name"
        required: true

jobs:
  BaseAmazonLinux:
    name: BuildSelectedImage
    uses: uc-cdis/.github/.github/workflows/image_build_push.yaml@master
    with:
      DOCKERFILE_LOCATION: "./${{ github.event.inputs.image }}/Dockerfile"
      OVERRIDE_REPO_NAME: "${{ github.event.inputs.image }}"
      OVERRIDE_TAG_NAME: "latest"
    secrets:
      ECR_AWS_ACCESS_KEY_ID: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
      ECR_AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_ROBOT_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}
