name: Main GitHub Action Workflow

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    uses: ./.github/workflows/my-reusable-workflow.yml

    steps:
    - name: Determine if changes are in the specific folder
      id: check_changes
      run: |
        CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
        if echo "$CHANGED_FILES" | grep -q "^specific-folder/"; then
          echo "::set-output name=changes::true"
        else
          echo "::set-output name=changes::false"
        fi

    - name: Build and Deploy Job
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        # Your build and deployment commands go here

