name: AmazonLinux Base Image Build on Push

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag to apply to this build. Defaults to 'latest'."
        default: "latest"
        required: false
  push:
    paths:
      - amazonlinux-base/**
  schedule:
    - cron: '0 0 * * 5' # Weekly on Saturday at 00:00

jobs:
  AmazonLinuxBase2023:
    name: Build AmazonLinux base image
    uses: uc-cdis/.github/.github/workflows/image_build_push.yaml@master
    with:
      DOCKERFILE_LOCATION: "./amazonlinux-base/Dockerfile"
      OVERRIDE_REPO_NAME: "amazonlinux-base"
      OVERRIDE_TAG_NAME: "$(echo ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || format('{0}', github.head_ref || github.ref_name) }} | tr / _)"
    secrets: inherit
