name: AmazonLinux Base Image Build on Push

on:
  push:
    paths:
      - amazonlinux-base/**

jobs:
  AmazonLinuxBase:
    name: AmazonLinuxBase2023
    uses: uc-cdis/.github/.github/workflows/image_build_push.yaml@master
    with:
      DOCKERFILE_LOCATION: "./amazonlinux-base/Dockerfile"
      OVERRIDE_REPO_NAME: "amazonlinux-base"
      OVERRIDE_TAG_NAME: "amazonlinux-base-$(echo ${GITHUB_REF#refs/*/} | tr / _)"
    secrets:
      ECR_AWS_ACCESS_KEY_ID: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
      ECR_AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_ROBOT_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}
