name: Rollout-Operator Image Build on Push

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag to apply to this build. Defaults to 'latest'."
        default: "latest"
        required: false
  push:
    paths:
      - rollout-operator/**
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday at 00:00

jobs:
  RolloutOperatorBuildBase:
    name: Build Rollout-Operator image
    uses: uc-cdis/.github/.github/workflows/image_build_push.yaml@master
    with:
      DOCKERFILE_LOCATION: "./rollout-operator/Dockerfile"
      OVERRIDE_REPO_NAME: "rollout-operator"
      OVERRIDE_TAG_NAME: "$(echo ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || format('{0}', github.head_ref || github.ref_name) }} | tr / _)"
      BUILD_PLATFORMS: "linux/amd64"
      DOCKERFILE_BUILD_CONTEXT: "./rollout-operator"
    secrets: inherit