name: Sync Registry
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync From Docker Hub to Aliyun
        uses: onichandame/docker-registry-sync-action@master
        with:
          source_repository: registry.hub.docker.com/alpine:3.10.2, 3.10.4, 3.11.3, 3.12.0, 3.13.5, 3.15.4, 3.6.2, 3.7.1, 3.7.3, 3.8.0, 3.9.0
          source_username: ${{ secrets.DOCKER_USERNAME }}
          source_password: ${{ secrets.DOCKER_PASSWORD }}
          target_repository: https://quay.io/repository/cdis/gen3-base-images/nginx:latest
          target_username: ${{ secrets.QUAY_USERNAME }}
          target_password: ${{ secrets.QUAY_ROBOT_TOKEN }}
