name: Weekly Image Build
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6' # Weekly on Saturday at 00:00

jobs:
  AWS_ES_PROXY:
    name: AmazonLinuxLatest
    uses: uc-cdis/.github/.github/workflows/image_build_push.yaml@master
    with:
      DOCKERFILE_LOCATION: "./aws-es-proxy/Dockerfile"
      OVERRIDE_REPO_NAME: "amazonlinux"
      OVERRIDE_TAG_NAME: "aws-es-proxy"
    secrets:
      ECR_AWS_ACCESS_KEY_ID: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
      ECR_AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_ROBOT_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}
  Golang_base:
    name: AmazonLinuxLatest
    uses: uc-cdis/.github/.github/workflows/image_build_push.yaml@master
    with:
      DOCKERFILE_LOCATION: "./goland_base/Dockerfile"
      OVERRIDE_REPO_NAME: "amazonlinux"
      OVERRIDE_TAG_NAME: "golang_base"
    secrets:
      ECR_AWS_ACCESS_KEY_ID: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
      ECR_AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_ROBOT_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}
  BasePython39:
    name: Python3.9
    uses: uc-cdis/.github/.github/workflows/image_build_push.yaml@master
    with:
      DOCKERFILE_LOCATION: "./python_base/python3.9/Dockerfile"
      OVERRIDE_REPO_NAME: "amazonlinux"
      OVERRIDE_TAG_NAME: "python3.9-latest"
    secrets:
      ECR_AWS_ACCESS_KEY_ID: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
      ECR_AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_ROBOT_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}